# Generated by Django 3.2.7 on 2021-09-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(blank=True, default='SK_custom.jpg', null=True, upload_to='')),
            ],
        ),
    ]
