# Generated by Django 3.2.7 on 2021-09-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
