# Generated by Django 3.2.7 on 2021-09-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spike', '0002_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(blank=True, default='SK_custom.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(blank=True, default='SK_custom.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(blank=True, default='SK_custom.jpg', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('featured_image', models.ImageField(blank=True, default='SK_custom.jpg', null=True, upload_to='')),
            ],
        ),
    ]
